export const SEED_LISTINGS = [
  { legacyId: '1', title: 'Электрик — проводка и щитки', category: 'construction', subcategory: 'electricians', description: 'Монтаж проводки, розеток, освещения. Заземление, замена щитков, подключение генератора.', priceFrom: 800, unit: 'час', rating: 4.8, reviewsCount: 24, lat: 54.6248, lng: 56.1080, address: 'п. Нагаево, ул. Советская, 27', phone: '+7 (347) 123-45-01', isVerified: true },
  { legacyId: '2', title: 'Аренда трактора МТЗ 80 л.с.', category: 'machinery', subcategory: 'agri-machinery', description: 'Трактор с навесным оборудованием. Вспашка, культивация, покос, перевозка грузов по Нагаево.', priceFrom: 2500, unit: 'день', rating: 4.9, reviewsCount: 18, lat: 54.6241, lng: 56.1087, address: 'п. Нагаево, ул. Полевая, 12', phone: '+7 (347) 234-56-02', isVerified: true },
  { legacyId: '3', title: 'Ремонт крыши — металлочерепица', category: 'construction', subcategory: 'roofers', description: 'Монтаж и ремонт кровли. Металлочерепица, профнастил, мягкая кровля. Выезд по всему селу.', priceFrom: 450, unit: 'м²', rating: 4.7, reviewsCount: 31, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, Нагаевское шоссе, 45', phone: '+7 (347) 345-67-03', isVerified: false },
  { legacyId: '4', title: 'Ассенизатор — откачка септиков', category: 'utility', subcategory: 'septic-service', description: 'Откачка септиков, выгребных ям. Промывка канализации. Работаем по Нагаево и прилегающим СНТ.', priceFrom: 3500, unit: 'услуга', rating: 4.6, reviewsCount: 42, lat: 54.6247, lng: 56.1079, address: 'п. Нагаево, ул. Рощинская, 15', phone: '+7 (347) 456-78-04', isVerified: true },
  { legacyId: '5', title: 'Экскаватор — земляные работы', category: 'machinery', subcategory: 'earthmoving', description: 'Копка траншей, котлованов под фундамент и септик. Колесный экскаватор, быстрый выезд.', priceFrom: 1800, unit: 'час', rating: 4.9, reviewsCount: 15, lat: 54.6250, lng: 56.1086, address: 'п. Нагаево, ул. Механизаторов, 8', phone: '+7 (347) 567-89-05', isVerified: true },
  { legacyId: '6', title: 'Сантехник — монтаж и ремонт', category: 'construction', subcategory: 'plumbers', description: 'Установка сантехники, замена труб, монтаж бойлеров и водоснабжения в частных домах.', priceFrom: 700, unit: 'час', rating: 4.5, reviewsCount: 19, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Лесная, 6', phone: '+7 (347) 678-90-06', isVerified: false },
  { legacyId: '7', title: 'Уборка домов и участков', category: 'staff', subcategory: 'cleaners', description: 'Генеральная уборка, поддерживающая уборка, мытьё окон. Работаю в Нагаево и ближайших посёлках.', priceFrom: 500, unit: 'час', rating: 4.7, reviewsCount: 11, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Запрудная, 1, к. 1', phone: '+7 (347) 789-01-07', isVerified: true },
  { legacyId: '8', title: 'Газель — переезды и доставка', category: 'logistics', subcategory: 'country-move', description: 'Дачные и квартирные переезды, доставка мебели и стройматериалов по Уфе и Нагаево.', priceFrom: 1200, unit: 'час', rating: 4.6, reviewsCount: 27, lat: 54.6243, lng: 56.1085, address: 'п. Нагаево, ул. Центральная, 18', phone: '+7 (347) 890-12-08', isVerified: true },
  { legacyId: '9', title: 'Вспашка и культивация огорода', category: 'farming', subcategory: 'plowing', description: 'Вспашка мотоблоком и трактором, культивация, боронование. Сезонная запись заранее.', priceFrom: 1500, unit: 'услуга', rating: 4.8, reviewsCount: 22, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Полевая, 34', phone: '+7 (347) 901-23-09', isVerified: true },
  { legacyId: '10', title: 'Юрист — земельные и жилищные вопросы', category: 'pro', subcategory: 'lawyers', description: 'Оформление участков, споры с застройщиками, договоры аренды. Консультации очно и онлайн.', priceFrom: 2000, unit: 'услуга', rating: 4.9, reviewsCount: 9, lat: 54.6246, lng: 56.1084, address: 'п. Нагаево, ул. Советская, 20а', phone: '+7 (347) 012-34-10', isVerified: true },
  { legacyId: '11', title: 'Дрова колотые — доставка по Нагаево', category: 'sales', subcategory: 'firewood-sales', description: 'Берёза и смешанные дрова, колотые и в чурбаках. Доставка газелью, разгрузка по договорённости.', priceFrom: 4500, unit: 'услуга', rating: 4.5, reviewsCount: 33, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, Нагаевское шоссе, 78', phone: '+7 (347) 123-56-11', isVerified: false },
  { legacyId: '12', title: 'Маникюр и педикюр на дому', category: 'beauty', subcategory: 'nails', description: 'Классический и аппаратный маникюр, покрытие гель-лаком, педикюр. Стерильные инструменты.', priceFrom: 1200, unit: 'услуга', rating: 4.9, reviewsCount: 41, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Молодёжная, 9', phone: '+7 (347) 234-67-12', isVerified: true },
  { legacyId: '13', title: 'Бурение скважин на воду', category: 'utility', subcategory: 'water', description: 'Бурение скважин, установка насосов, обустройство водоснабжения в частных домах Нагаево.', priceFrom: 2500, unit: 'м²', rating: 4.7, reviewsCount: 14, lat: 54.6249, lng: 56.1078, address: 'п. Нагаево, ул. Садовая, 22', phone: '+7 (347) 345-78-13', isVerified: true },
  { legacyId: '14', title: 'Мужская стрижка и борода', category: 'beauty', subcategory: 'barber', description: 'Барбершоп на дому: стрижки, оформление бороды, камуфляж седины. Запись через мессенджер.', priceFrom: 600, unit: 'услуга', rating: 4.8, reviewsCount: 28, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Рощинская, 45', phone: '+7 (347) 456-89-14', isVerified: true },
  { legacyId: '15', title: 'Вывоз строительного мусора', category: 'utility', subcategory: 'waste', description: 'Вывоз мусора после ремонта, старых заборов, веток. Контейнер 8 м³ или бортовая машина.', priceFrom: 4000, unit: 'услуга', rating: 4.4, reviewsCount: 16, lat: 54.6242, lng: 56.1084, address: 'п. Нагаево, ул. Механизаторов, 27', phone: '+7 (347) 567-90-15', isVerified: false },
  { legacyId: '16', title: 'Садовник — обрезка и уход', category: 'staff', subcategory: 'gardeners', description: 'Обрезка деревьев и кустарников, весенняя и осенняя уборка участка, посадка газона.', priceFrom: 600, unit: 'час', rating: 4.7, reviewsCount: 20, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Садовая, 5', phone: '+7 (347) 678-01-16', isVerified: true },
  { legacyId: '17', title: 'Монтаж окон ПВХ и балконов', category: 'construction', subcategory: 'glazing', description: 'Установка пластиковых окон, остекление балконов, регулировка фурнитуры. Замер бесплатно.', priceFrom: 8500, unit: 'услуга', rating: 4.6, reviewsCount: 13, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, Нагаевское шоссе, 12', phone: '+7 (347) 789-12-17', isVerified: true },
  { legacyId: '18', title: 'Эвакуатор — круглосуточно', category: 'logistics', subcategory: 'evacuator', description: 'Эвакуация легковых авто и микроавтобусов. Нагаево, Уфа, трасса М-5. Быстрый подъём.', priceFrom: 2500, unit: 'услуга', rating: 4.5, reviewsCount: 38, lat: 54.6251, lng: 56.1090, address: 'п. Нагаево, центр', phone: '+7 (347) 890-23-18', isVerified: true },
  { legacyId: '19', title: 'Установка септиков «Топас» и «Юнилос»', category: 'utility', subcategory: 'septic-install', description: 'Продажа и монтаж септиков, дренаж, подключение к дому. Гарантия на монтажные работы.', priceFrom: 45000, unit: 'услуга', rating: 4.8, reviewsCount: 7, lat: 54.6248, lng: 56.1087, address: 'п. Нагаево, ул. Лесная, 14', phone: '+7 (347) 901-34-19', isVerified: true },
  { legacyId: '20', title: 'Репетитор по математике и физике', category: 'pro', subcategory: 'tutors', description: 'Подготовка к ОГЭ и ЕГЭ, помощь школьникам 5–11 классов. Занятия у ученика или онлайн.', priceFrom: 800, unit: 'час', rating: 5.0, reviewsCount: 12, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Запрудная, 7', phone: '+7 (347) 012-45-20', isVerified: true },
  { legacyId: '21', title: 'Покос травы и скашивание бурьяна', category: 'farming', subcategory: 'mowing', description: 'Покос триммером и косилкой на больших участках. Уборка и вывоз скошенной травы по желанию.', priceFrom: 800, unit: 'час', rating: 4.6, reviewsCount: 17, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Полевая, 8', phone: '+7 (347) 123-67-21', isVerified: false },
  { legacyId: '22', title: 'Песок, щебень, чернозём с доставкой', category: 'sales', subcategory: 'bulk-materials', description: 'Сыпучие материалы для стройки и ландшафта. Доставка самосвалом по Нагаево и району.', priceFrom: 3200, unit: 'услуга', rating: 4.5, reviewsCount: 25, lat: 54.6240, lng: 56.1085, address: 'п. Нагаево, Нагаевское шоссе, 102', phone: '+7 (347) 234-78-22', isVerified: true },
  { legacyId: '23', title: 'Строительство бань и хозблоков', category: 'construction', subcategory: 'builders', description: 'Каркасные и брусовые бани под ключ, хозблоки, беседки. Проект и смета бесплатно.', priceFrom: 180000, unit: 'услуга', rating: 4.7, reviewsCount: 6, lat: 54.6245, lng: 56.1082, address: 'п. Нагаево, ул. Молодёжная, 22', phone: '+7 (347) 345-89-23', isVerified: true },
  { legacyId: '24', title: 'Фотограф — семейные и праздничные съёмки', category: 'pro', subcategory: 'photographers', description: 'Фотосессии в Нагаево и на природе, выпускные, дни рождения, репортаж с мероприятий ДК.', priceFrom: 3500, unit: 'услуга', rating: 4.9, reviewsCount: 19, lat: 54.6247, lng: 56.1081, address: 'п. Нагаево, ДК', phone: '+7 (347) 456-90-24', isVerified: true },
] as const

export const SEED_FORUM_TOPICS = [
  { title: 'Какой септик лучше для дачи в Нагаево — Топас или Юнилос?', category: 'septic', authorName: 'Сергей', content: 'Планирую установку септика на участке. Кто пользовался Топасом или Юнилосом в наших условиях?', isPinned: true },
  { title: 'Ищу электрика для подключения генератора на Запрудной', category: 'electric', authorName: 'Ольга', content: 'Нужен мастер для подключения генератора к дому. Подскажите проверенных.', isPinned: false },
  { title: 'Аренда экскаватора в Нагаево — кто брал на Механизаторов?', category: 'machinery', authorName: 'Дмитрий', content: 'Ищу отзывы по аренде экскаватора для котлована под септик.', isPinned: false },
  { title: 'Ремонт крыши после зимы — советы для наших домов', category: 'construction', authorName: 'Николай', content: 'После зимы пошли протечки. Какие материалы лучше держатся в нашем климате?', isPinned: false },
  { title: 'Где заказать дрова с доставкой по селу?', category: 'general', authorName: 'Виктор', content: 'Нужны берёзовые дрова с доставкой на Нагаевское шоссе.', isPinned: false },
  { title: 'Водопровод на зиму — как утеплить трубы?', category: 'plumbing', authorName: 'Айрат', content: 'Какие способы утепления работают у вас на даче?', isPinned: false },
  { title: 'Рекомендации барбера в Нагаево', category: 'beauty', authorName: 'Максим', content: 'Ищу мастера на дом для стрижки и бороды.', isPinned: false },
  { title: 'Вывоз строительного мусора после ремонта — цены', category: 'cleaning', authorName: 'Татьяна', content: 'Сколько сейчас берут за вывоз мусора после ремонта бани?', isPinned: false },
] as const

export const SEED_REVIEWS: Record<string, [string, string]> = {
  '1': ['Электрик приехал быстро, всё сделал качественно. Проводку в доме полностью заменили, щиток собрали аккуратно.', 'Меняли розетки и освещение на даче. Мастер объяснил, что именно менял.'],
  '2': ['Тракторист отличный — вспахал огород на Полевой за полдня. Цена адекватная.', 'Арендовали МТЗ для культивации участка. Техника исправная, оператор опытный.'],
  '10': ['Юрист помог оформить земельный участок. Документы подготовили без ошибок.', 'Консультация по договору аренды сэкономила время и нервы.'],
  '20': ['Репетитор помог дочери подготовиться к ОГЭ по математике.', 'Занятия по физике для 10 класса — понятные объяснения.'],
}
