/** Параметры карты Leaflet */
const MAP_BOUNDS_VISCOSITY = 0.85

/** Маркер текущего местоположения пользователя */
const USER_LOCATION_MARKER_RADIUS = 10
const USER_LOCATION_MARKER_STROKE_WEIGHT = 2
const USER_LOCATION_MARKER_FILL_OPACITY = 0.85

export {
  MAP_BOUNDS_VISCOSITY,
  USER_LOCATION_MARKER_RADIUS,
  USER_LOCATION_MARKER_STROKE_WEIGHT,
  USER_LOCATION_MARKER_FILL_OPACITY,
}
