/** HTTP и UI-тайминги */
const API_TIMEOUT_MS = 15000;
const UPLOAD_TIMEOUT_MS = 300_000;
const TOAST_DURATION_MS = 4000;
const FORM_SUBMIT_DELAY_MS = 500;
/** Ограничения длины текста */
const META_DESCRIPTION_MAX_LENGTH = 160;
const NEWS_SUMMARY_MAX_LENGTH = 180;
/** Лимиты списков и превью */
const NEWS_LOCAL_LIMIT = 8;
const NEWS_REFRESH_MS = 5 * 60 * 1000;
const LOCATION_REMINDER_MS = 2 * 60 * 1000;
const SIMILAR_LISTINGS_LIMIT = 3;
const REVIEW_PREVIEW_LIMIT = 3;
const MAP_CATEGORY_FILTER_LIMIT = 6;
const SKELETON_COUNT_DEFAULT = 3;
const SKELETON_COUNT_NEWS = 4;
const MAX_LISTING_PHOTOS = 10;
/** Рейтинг и карта */
const MAX_RATING = 5;
const MAP_BOUNDS_PADDING_PX = 32;
const MAP_CONTROL_Z_INDEX = 1000;
/** Размеры логотипа (px) */
const LOGO_ICON_SIZE_DEFAULT = 52;
const LOGO_ICON_SIZE_COMPACT = 46;
const HERO_STAMP_SIZE = 360;
const SCROLL_ROTATION_FACTOR = 0.18;

export {
  API_TIMEOUT_MS,
  UPLOAD_TIMEOUT_MS,
  TOAST_DURATION_MS,
  FORM_SUBMIT_DELAY_MS,
  META_DESCRIPTION_MAX_LENGTH,
  NEWS_SUMMARY_MAX_LENGTH,
  NEWS_LOCAL_LIMIT,
  NEWS_REFRESH_MS,
  LOCATION_REMINDER_MS,
  SIMILAR_LISTINGS_LIMIT,
  REVIEW_PREVIEW_LIMIT,
  MAP_CATEGORY_FILTER_LIMIT,
  SKELETON_COUNT_DEFAULT,
  SKELETON_COUNT_NEWS,
  MAX_LISTING_PHOTOS,
  MAX_RATING,
  MAP_BOUNDS_PADDING_PX,
  MAP_CONTROL_Z_INDEX,
  LOGO_ICON_SIZE_DEFAULT,
  LOGO_ICON_SIZE_COMPACT,
  HERO_STAMP_SIZE,
  SCROLL_ROTATION_FACTOR,
}
