import type { LucideIcon } from 'lucide-react';
import {
  Angry,
  Backpack,
  Bell,
  Briefcase,
  Brush,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ClipboardList,
  Clock,
  CloudRain,
  Coffee,
  Compass,
  CreditCard,
  Eye,
  Flame,
  Forward,
  Frown,
  Gift,
  Hammer,
  Hand,
  Heart,
  Home,
  Key,
  Laugh,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  MoreVertical,
  Package,
  Paperclip,
  PartyPopper,
  PawPrint,
  Phone,
  Plus,
  Scissors,
  Search,
  Send,
  ShoppingBag,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  Star,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Tractor,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Wheat,
  Wrench,
  Zap,
} from 'lucide-react';
import type { AppIconName } from '@/types/icon';

const ICON_REGISTRY: Record<AppIconName, LucideIcon> = {
  hammer: Hammer,
  tractor: Tractor,
  brush: Brush,
  home: Home,
  truck: Truck,
  wheat: Wheat,
  briefcase: Briefcase,
  shopping: ShoppingBag,
  scissors: Scissors,
  wrench: Wrench,
  zap: Zap,
  megaphone: Megaphone,
  messages: MessageCircle,
  clipboard: ClipboardList,
  search: Search,
  heart: Heart,
  smartphone: Smartphone,
  compass: Compass,
  sparkles: Sparkles,
  users: Users,
  car: Car,
  package: Package,
  key: Key,
  paw: PawPrint,
  backpack: Backpack,
  card: CreditCard,
  help: CircleHelp,
  clock: Clock,
  paperclip: Paperclip,
  mic: Mic,
  send: Send,
  stop: Square,
  menu: MoreVertical,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  star: Star,
  bell: Bell,
  smile: Smile,
  forward: Forward,
  plus: Plus,
  mapPin: MapPin,
  laugh: Laugh,
  frown: Frown,
  angry: Angry,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  hand: Hand,
  party: PartyPopper,
  flame: Flame,
  trophy: Trophy,
  coffee: Coffee,
  utensils: UtensilsCrossed,
  sun: Sun,
  moon: Moon,
  cloud: CloudRain,
  phone: Phone,
  mail: Mail,
  gift: Gift,
  check: Check,
  eye: Eye,
};

export {
  ICON_REGISTRY,
};
